#!/usr/bin/env python3
'''
This module contains the async_comprehension coroutine, which collects 10 random
float values using async_generator with an async comprehension.
'''

import asyncio
from typing import List  # Import List from typing for type annotations

# Assuming async_generator is imported from another module
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    '''
    Collects 10 random float values using an async comprehension over async_generator.
    
    This coroutine asynchronously collects 10 random float values generated by 
    async_generator() and returns them as a list of floats.
    
    The returned list contains **only float values**.
    
    Returns:
        List[float]: A list of 10 random float numbers yielded by async_generator.
    
    Example:
        >>> result = await async_comprehension()
        >>> len(result)
        10
        >>> all(isinstance(i, float) for i in result)
        True
    '''
    try:
        # Use async comprehension to collect 10 random numbers
        result = [i async for i in async_generator()][:10]
        
        # Debugging: Check if all values are floats
        print(all(isinstance(i, float) for i in result))  # This should print True
        return result
    except Exception as e:
        print(f"Error occurred: {e}")
        return None
